language: rust
rust:
  - stable
  - 1.30.0
  - 1.30.1
matrix:
  - env: TARGET=x86_64-pc-windows-gnu
  - env: TARGET=i686-pc-windows-gnu
  fast_finish: true

os: windows

script:
  - cargo build --verbose --all
  - cargo test --verbose --all


provider: releases

skip_cleanup: true

